### PR TITLE
Add Prioritize.py

### PR DESCRIPTION
**Pull request by crsegerie**
Summary:
- memoization
- Diversity sampling
- Refacto

### CODE REVIEW

**Review by PierreLeveau — APPROVED** [review]
LGTM

**Comment by PierreLeveau** [comment]
waiting for commit squash and local testing before merging

**Comment by crsegerie** [comment]
Local tests succesfull

**Comment by PierreLeveau** [comment]
You can change the commit message to: `feat(ML-24): add prioritize with diversity sampling`, solve the conflict and we should be good!

**Pull request merged**
