### PR TITLE
fix: add dotenv install to notebook

### PR DESCRIPTION
**Pull request by antonioloison**
- add dotenv package install to notebooks

### CODE REVIEW

**Comment by antonioloison** [comment]
flake8 is detecting a missing abstractmethod in `KiliTextProjectMixin` is it normal? @crsegerie

**Comment by PierreLeveau** [comment]
Why do we need to install `dot-env` separately ?

**Comment by antonioloison** [comment]
> Why do we need to install `dot-env` separately ?

When you use the notebook locally, you need to have a `.env` file with the API key and dotenv is needed to find the file.

**Comment by PierreLeveau** [comment]
you can change `class HuggingFaceMixin(metaclass=ABCMeta):` to  `class HuggingFaceMixin():` then

**Comment by PierreLeveau** [comment]
oops duplicate

**Pull request closed without merging**
